# Generated by Django 5.2.4 on 2025-10-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Chat ID в Telegram"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Username в Telegram"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата подключения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram пользователь",
                "verbose_name_plural": "Telegram пользователи",
            },
        ),
    ]
